<?php

namespace App\Libraries\CryptoPro\CAdESCOM\Constants;

class CADESCOM_ATTRIBUTE
{
    const CADESCOM_ATTRIBUTE_OTHER = 4294967295;
    const CADESCOM_AUTHENTICATED_ATTRIBUTE_DOCUMENT_DESCRIPTION = 2;
    const CADESCOM_AUTHENTICATED_ATTRIBUTE_DOCUMENT_NAME = 1;
    const CADESCOM_AUTHENTICATED_ATTRIBUTE_SIGNING_TIME = 0;
}