<?php

namespace App\Libraries\CryptoPro\CAdESCOM\Constants;

class CADESCOM_ENCRYPTION_ALGORITHM
{
    const CADESCOM_ENCRYPTION_ALGORITHM_3DES = 3;
    const CADESCOM_ENCRYPTION_ALGORITHM_AES = 4;
    const CADESCOM_ENCRYPTION_ALGORITHM_DES = 2;
    const CADESCOM_ENCRYPTION_ALGORITHM_GOST_28147_89 = 25;
    const CADESCOM_ENCRYPTION_ALGORITHM_RC2 = 0;
    const CADESCOM_ENCRYPTION_ALGORITHM_RC4 = 1;
}