<?php

namespace App\Libraries\CryptoPro\CAdESCOM\Constants;

class CAPICOM_HASH_ALGORITHM
{
    const CAPICOM_HASH_ALGORITHM_SHA1 = 0;
    const CAPICOM_HASH_ALGORITHM_MD2 = 1;
    const CAPICOM_HASH_ALGORITHM_MD4 = 2;
    const CAPICOM_HASH_ALGORITHM_MD5 = 3;
    const CAPICOM_HASH_ALGORITHM_SHA_256 = 4;
    const CAPICOM_HASH_ALGORITHM_SHA_384 = 5;
    const CAPICOM_HASH_ALGORITHM_SHA_512 = 6;

}